{% set name = "mo-kwargs" %}
{% set version = "7.606.24115" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: df2180a7ea73aca006243d61d7846528c444d75e6caf3c9ec903ccbd3a20c7d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.606.24115
    - mo-future ==7.531.24035

test:
  imports:
    - mo_kwargs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-kwargs
  summary: More KWARGS! Let call parameters override kwargs
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
