{% set name = "mo-kwargs" %}
{% set version = "7.230.22310" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-kwargs-{{ version }}.tar.gz
  sha256: 3950790da31cfe8d9d556e88ac6ed154dbb1ee985413d80cbe30e55707c4c051

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.230.22310
    - mo-future ==6.230.22310

test:
  imports:
    - mo_kwargs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-kwargs
  summary: More KWARGS! Let call parameters override kwargs
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
